# Uncomment the next line to define a global platform for your project
platform :ios, '18.0'

target 'demo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for demo
  pod 'CellRebelSDK', :git => 'https://github.com/cellrebel/CellRebelSDK-iOS.git', :tag => '1.5.0-beta'
end
